--CREATE DATABASE INVENTARIO
--USE INVENTARIO

CREATE DATABASE INVENTARIO
USE INVENTARIO

CREATE TABLE USUARIOS(
IDUSUARIOS INT NOT NULL PRIMARY KEY IDENTITY(1,1), -- SQL DE ORACLE ES AUTO_INCREMENT
NOMBRECOMPLETO VARCHAR(150) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
PASSWRD VARCHAR(100) NOT NULL,
TIPOUSUARIO VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTAMENTOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRED VARCHAR(50) NOT NULL,
DESCRIPCION TEXT
);

CREATE TABLE PUESTOS(
IDPUESTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBREP VARCHAR(50) NOT NULL,
DESCRIPCION TEXT
);

CREATE TABLE EMPLEADOS(
IDEMPLEADO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(150) NOT NULL,
IDENTIDAD VARCHAR(20) NOT NULL,
GENERO VARCHAR(20),
TELEFONO VARCHAR(20),
CORREO VARCHAR(100),
DIRECCION TEXT,
IDPUESTO INT NOT NULL,
IDDEPARTAMENTO INT NOT NULL,
CONSTRAINT FK_IDPUESTO FOREIGN KEY (IDPUESTO) REFERENCES PUESTOS(IDPUESTO),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID)
);

CREATE TABLE MARCAS(
IDMARCA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBREM VARCHAR(50) NOT NULL,
DESCRIPCION TEXT 
);

CREATE TABLE ARTICULOS(
IDARTICULO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBREA VARCHAR(50) NOT NULL,
NUMEROSERIE VARCHAR(50) NOT NULL,
CODIGOA VARCHAR(50) NOT NULL,
IDMARCA INT NOT NULL,
MODELO VARCHAR(50),
PRECIOCOMPRA MONEY NOT NULL,
FECHACOMPRA DATE NOT NULL,
ESTADOARTICULO VARCHAR(50) NOT NULL,
DESCRIPCION TEXT
CONSTRAINT FK_IDMARCA FOREIGN KEY (IDMARCA) REFERENCES MARCAS(IDMARCA)
)

CREATE TABLE CARGODEACTIVOS(
IDCARGO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CODIGOINVENTARIO VARCHAR(50) NOT NULL,
FECHAASIGNACION DATE NOT NULL,
ESTADOARTICULO VARCHAR(50) NOT NULL,
DESCRIPCION TEXT,
IDARTICULO INT NOT NULL,
IDEMPLEADO INT NOT NULL,
CONSTRAINT FK_IDEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS(IDEMPLEADO),
CONSTRAINT FK_IDARTICULO FOREIGN KEY (IDARTICULO) REFERENCES ARTICULOS(IDARTICULO)
);

CREATE TABLE DescargoACTIVOS(
iddescargo int not null primary key identity(1,1),
fechadescargo date not null,
descripcion text,
motivodescargo varchar(50),
IdCargo int not null,
CONSTRAINT FK_IDCARGO FOREIGN KEY (IDCARGO) REFERENCES CARGODEACTIVOS(IDCARGO)
);

-- en sql server se pueden hacer foreign keys rapidamente usando el diagrama, aunque tambien puede hacerse por codigo
-- ver errores 

-- relacionar en FK_Empleados_Puestos
-- PUESTOS.IdPuesto con EMPLEADOS.IdPuesto
-- PUESTOS CONTIENE LA PK A ASOCIAR A LA FK DE EMPLEADOS

-- PREVIAMENTE HAY QUE DEFINIR LAS CANDIDATAS
--ver syntax en transact, sino usar sql de oracle, aunque para eso debe reemplazarse los identity por autoincrements

---- VER CONSTRAINT INTERNO

-- FK_Empleados_Departamentos
-- DEPARTAMENTOS.IdDepartamento con EMPLEADOS.IdDEPARTAMENTO

-- FK_Articulos_Marcas
-- MARCAS.IdMarca con ARTICULOS.IdMarca

-- FK_CARGODEACTIVOS_ARTICULOS
-- ARTICULOS.IDArticulo con CARGOACTIVOS.IDArticulo

-- FK_EMPLEADOS_CARGODEACTIVOS
-- EMPLEADOS.IDEMPLEADO con CARGODEACTIVOS.IDEMPLEADO

-- FK_CARGODEACTIVOS_DESCARGOACTIVOS
-- CARGODEACTIVOS.IDCARGO con DESCARGOACTIVOS.IDCARGO
