-- CODIGO ADAPTABLE A LAS OTRAS TABLAS PARA INSERTAR DATOS

CREATE PROCEDURE SP_InsertarEmpleado
(
	@NOMBRE VARCHAR(150),
	@IDENTIDAD VARCHAR(20),
	@GENERO VARCHAR(20),
	@TELEFONO VARCHAR(20),
	@CORREO VARCHAR(100),
	@DIRECCION TEXT,
	@IDPUESTO INT,
	@IDDEPARTAMENTO INT
)
AS
	IF EXISTS(SELECT IDENTIDAD FROM EMPLEADOS WHERE IDENTIDAD = @IDENTIDAD)
		PRINT('REGISTRO EXISTENTE EN TABLA DE EMPLEADOS')
	ELSE
BEGIN
	INSERT INTO EMPLEADOS(NOMBRE, IDENTIDAD, GENERO, TELEFONO, CORREO, DIRECCION, IDPUESTO, IDDEPARTAMENTO)
		VALUES(@NOMBRE, @IDENTIDAD, @GENERO, @TELEFONO, @CORREO, @DIRECCION, @IDPUESTO, @IDDEPARTAMENTO)
		PRINT('EMPLEADO REGISTRADO EXITOSAMENTE')
END
GO

-- SEGUNDA PARTE

EXECUTE SP_InsertarEmpleado 'Dev Lang', '28012021', 'Masculino', '5555-5555', 'mail@mohmal.com', 'Argentina',1,1
